[build]
  publish = "dist"
  command = "npm run build"

# Rediriger /api/send-email vers la fonction serverless
[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
  force = true
